version: '3.4'

services:
  
  server-messaging:
    container_name: server-messaging
    hostname: server-messaging
    image: rabbitmq:3-management
    ports: 
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=docker
      - RABBITMQ_DEFAULT_PASS=123
    networks: 
      server-node:
        aliases: 
          - "server-messaging"

  #################################################################################
  # SERVER-NODE
  #################################################################################

  server:
    container_name: server
    hostname: server
    image: cams-resource-server 
    restart: always
    ports: 
      - "8081:8081"
      - "5005:5005"
    volumes: 
      - /home/pedro/workspace/cams/cams-resource-server/:/server/
      - $HOME/.m2:/root/.m2
    environment:
      - PROFILE=server_docker
      - MESSAGING_BROKER_URL=server-messaging
      - MESSAGING_BROKER_PORT=5672
      - DEBUG_PORT=5006
    networks: 
      server-node:
        aliases:
          - "server"
    links:
      - server-messaging
      - hub-server
  
  hub-server:
    container_name: hub-server
    hostname: hub-server
    image: cams-hub  
    restart: always
    ports:  
      - "8085:8085"
      - "8084:8084"
    volumes: 
      - /home/pedro/workspace/cams/cams-hub/:/hub/
    environment:
      - RESOURCE_SERVER_HOST=server
      - RESOURCE_SERVER_PORT=8081
      - RESOURCE_SERVER_URL=http://server:8081
    networks: 
      server-node:
        aliases:
          - "hub-server"
    links:
      - server-messaging

  server-front:
    container_name: server-front
    hostname: server-front
    image: cams-client
    restart: always
    stdin_open: true
    ports: 
      - "3000:3000"
      - "3001:3001"
    volumes:
      - /home/pedro/workspace/cams/cams-client/:/client/
      - /home/pedro/workspace/cams/cams-client/_logs/:/root/.npm/_logs
    environment: 
      - RESOURCE_HOST=server
      - RESOURCE_PORT=8081
      - RESOURCE_PROTOCOL=http
      - HUB_HOST=hub-server
      - HUB_OUT_PORT=8085
    networks: 
      server-node:
        aliases: 
          - "server-front"
  
  #################################################################################
  # CLIENT-NODE
  #################################################################################
  
  client:
    container_name: client
    hostname: client
    image: cams-resource-server 
    restart: always
    ports: 
      - "8082:8082"
      - "5007:5007"
    volumes: 
      - /home/pedro/workspace/cams/cams-resource-server/:/server/
      - $HOME/.m2:/root/.m2
    environment:
      - PROFILE=client_docker
      - MESSAGING_BROKER_URL=server-messaging
      - MESSAGING_BROKER_PORT=5672
      - DEBUG_PORT=5007
    networks: 
      server-node:
        aliases:
          - "client"
    links:
      - server-messaging
      - hub-client
  
  hub-client:
    container_name: hub-client
    hostname: hub-client
    image: cams-hub  
    restart: always
    ports:  
      - "8086:8586"
      - "8087:8487"
    volumes: 
      - /home/pedro/workspace/cams/cams-hub/:/hub/
    environment:
      - RESOURCE_SERVER_HOST=client
      - RESOURCE_SERVER_PORT=8082
      - RESOURCE_SERVER_URL=http://client:8082
    networks: 
      server-node:
        aliases: 
          - "hub-client"
    links:
      - server-messaging

networks:
  server-node:
    driver: bridge